name: Frontend Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Frontend Files
        uses: github/super-linter@v5
        env:
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}